name: Cancel
on:
  workflow_run:
    workflows: ["ci-workflow"]
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          workflow_id: 605175
